### ISSUE TITLE
Not very effective

### ISSUE THREAD

**Issue by Pantyhose-X** [Lemente/remove_lava#1]
The Remove speed is too slow.
If underch can propagate so quickly, it should be able to delete so quickly?
underch generates lava very quickly.
Remove underch and he doesn't generate any more.

[Remove the big lava video demo](https://www.theta.tv/video/vid8hqz6ay6k75g9zwq)
[A list of all the mods I use](https://github.com/Pantyhose-X/AllmodsIuse/releases/tag/lava)

**Comment by Lemente** [comment]
Updated the mod so lava flow is deactivated. It should help to some extent.
Sadly this mod is not meant to counter another mod actively generating lava. The error in the original mod needs to be fixed for that.

But it will stop lava and fire from spreading, and remove them in loaded mapblocks.

For faster results, you can edit the variables in init.lua :
```
local min_height=0;
local max_height=0;
local remove_lava = false
```
to
```
local min_height=0; -- from sea level
local max_height=30000; -- to map top
local remove_lava = true
```

this means the mod will be activated when you start the world, which will trigger the deletion when the mapblocks are being loaded, which is much faster than deleting nodes from already loaded mapblocks

hope this helps

**Comment by Lemente** [comment]
Updated the mod so lava flow is deactivated. It should help to some extent.
Sadly this mod is not meant to counter another mod actively generating lava. The error in the original mod needs to be fixed for that.

But it will stop lava and fire from spreading, and remove them in loaded mapblocks.

For faster results, you can edit the variables in init.lua :
```
local min_height=0;
local max_height=0;
local remove_lava = false
```
to
```
local min_height=0; -- from sea level
local max_height=30000; -- to map top
local remove_lava = true
```

this means the mod will be activated when you start the world, which will trigger the deletion when the mapblocks are being loaded, which is much faster than deleting nodes from already loaded mapblocks

hope this helps
